# Static display constants shared across the UI
APP_TITLE = "ROLLING THUNDER MULTI-PHYSICS & THERMODYNAMIC SIMULATOR"
APP_VERSION = "v1.0.0"
APP_HEADER = f"{APP_TITLE} {APP_VERSION}"

MODE_LABEL = "[ MODE: CONFIG ]"
